spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.80.128:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #ÈÃÖ÷¼ü×ÔÔö
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
